### ISSUE TITLE
allow for once off execution run

### ISSUE THREAD

**Issue by abate** [tiredofit/docker-mongodb-backup#1]
I often backup my db before running a critical update on the database. It would be very useful to be able to run the backup once on demand.

`DB_DUMP_BEGIN=+0 ./run/s6/services/10-mongodb-backup/run`

runs the script immediately, but it also start the cron loop.

Would it be possible either to refactor the script to decouple the cron job with the backup script, or simply to add a command line option to the `run` script to run it once and exit immediately ?

(a small restore script would also be very handy to have in the image)

**Comment by tiredofit** [comment]
Sure, that would be useful. I've actually invested my efforts into github.com/tiredofit/db-backup recently which is where I'd build the one off and restore scripts. I'll put it on the list when I have a bit of time to make some enhancements.

**Comment by tiredofit** [comment]
I've updated the [db-backup](https://github.com/tiredofit/docker-db-backup)  image to support manual backups. All you would need to do is enter the container and type `backup-now`. As for the restore, that will take a bit more thinking on how to effectively handle it. Hope this helps.

**Comment by abate** [comment]
This new image is basically as the `docker-mongodb-backup` except it works with multiple dbs ?

**Comment by tiredofit** [comment]
That's correct! And more features (parallel compression support, some cleanup of the code)
