### ISSUE TITLE
Empty backup file

### ISSUE THREAD

**Issue by kglazov** [tiredofit/docker-mongodb-backup#2]
Backup returning empty files to the backup folder. 
There is an example of my compose yaml. 

version: '3.1'

services:
  
  my-mongo:
    image: mongo:3.6.2
    hostname: tia-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_username
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
      - MONGO_INITDB_DATABASE=local
    volumes:
      - tia_mongo_data:/data/db
      - ./mongo/.dbshell:/root/.dbshell
    deploy:
      replicas: 1
   
      
  my-mongo-backup:
    image: tiredofit/mongodb-backup
    hostname: my-mongo-backup
    volumes:
      - ./mongo/backups:/backups
    environment:
      - DB_HOST=my-mongo
      - DB_NAME=local
      - DB_USER=mongo_username
      - DB_PASS=mongo_password
      # How often to do a dump, in minutes.
      - DB_DUMP_FREQ=1
      - DB_DUMP_BEGIN=+0
      - MD5=false
      - COMPRESSION=NONE
      - DB_DUMP_DEBUG=true
      # Value in minutes to delete old backups.
      - DB_CLEANUP_TIME=1
    deploy:
      replicas: 1

**Comment by tiredofit** [comment]
Could I point you over to a more featured/updated version of this image? https://github.com/tiredofit/docker-db-backup. I haven't touched this one in about 7 months and instead have been focusing my effort into one that is more suited to my needs right now.
