### ISSUE TITLE
Store dumps for latest several days and after remove

### ISSUE THREAD

**Issue by Mikkou** [tiredofit/docker-mongodb-backup#9]
Can I do with current settings to your service store dumps for latests several days (f.e. 7 days) and remove\create new dumps every day? Right now he creates new and remove at the same time if I wirte values in the variables for deleting and creating same time. First 7 dumps I don't want delete, but after them I want.

**Comment by tiredofit** [comment]
I suppose that could be done with adding a custom cron expression into the image to take over the cleanup process.  Remove the DB_CLEANUP variable and then map a volume to `/assets/cron-custom/` and drop a file in there called cleanup with a cron entry that does what you need.

**Comment by Mikkou** [comment]
@tiredofit ok, thanks!
